# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
  
julia:
  - 1.0
  - 1.1
  - 1.2
  - nightly
  
allow failures:
  - julia: nightly
  
fast_finish: true

#branches:
#  only:
#    - master
    
codecov: true

notifications:
  email: false
  
env:
 - PYTHON=""
  
# jobs:
#     include:
# 	- stage: "Documentation"
script:
  - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instanstiate()'
  - julia --project=docs/ docs/make.jl
      
after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
